### ISSUE TITLE
PURESTAKE API SCRIPT

### ISSUE THREAD

**Issue by Haitianwarrior** [CareBoo/unity-algorand-sdk#100]
Hey, thank you for this amazing SDK! Could you please guide me on how to edit the script to use the Purestake API for  ALGOD instead of sandbox? Thanks again.

**Comment by bernhardrieder** [comment]
Have a quick look at the last section in https://github.com/CareBoo/unity-algorand-sdk/blob/main/Documentation~/quickstart.md#connect-to-a-node. You just have to update the api key and you're good to go for testnet.
```
algod = new AlgodClient(
   "https://testnet-algorand.api.purestake.io/ps2",
   ("x-api-key", "my-super-secret-api-key")
);
```

**Comment by jasonboukheir** [comment]
closing this out, thanks @bernhardrieder !
