### ISSUE TITLE
Algorand Unity SDK deprecated in Unity Assets??

### ISSUE THREAD

**Issue by Vytek** [CareBoo/unity-algorand-sdk#152]
![Schermata 2022-07-25 alle 14 06 58](https://user-images.githubusercontent.com/2614303/180775691-ca367dbb-4cdd-4a20-8b36-38b6a8b9047f.png)

What??

**Comment by jasonboukheir** [comment]
Yep, Unity changed their asset requirements for any web3 assets recently, and marked all of them deprecated until they can get reapproved :(.

I'm still waiting to hear back on what I need to do to get reapproved.

**Comment by jasonboukheir** [comment]
Hey @Vytek , I'm working with Algorand Foundation to become a VSP with Unity and un-deprecate this asset in the Asset Store.

It's going to be a long process, and may require lots of changes for this project. In the meantime, please install via UPM or the .unitypackage file in the Releases.

**Comment by jasonboukheir** [comment]
keeping this issue open until the sdk can be back in the asset store. However locking it, as there is a workaround above ^^
