### ISSUE TITLE
Error importing and compiling Unity Algorand SDK version 3.0

### ISSUE THREAD

**Issue by Vytek** [CareBoo/unity-algorand-sdk#154]
This is the error on console:

Assets\AlgoSdk\Runtime\CareBoo.AlgoSdk.LowLevel\NativeOrderedSet.cs(14,9): error CS0246: The type or namespace name 'NativeParallelHashSet<>' could not be found (are you missing a using directive or an assembly reference?)

Unity Version: 2021.3.9f1 (Windows)

This is the manifest.json:

{
  "dependencies": {
    "com.unity.collab-proxy": "1.17.2",
    "com.unity.collections": "1.2.4",
    "com.unity.feature.development": "1.0.1",
    "com.unity.ide.rider": "3.0.15",
    "com.unity.ide.visualstudio": "2.0.16",
    "com.unity.ide.vscode": "1.2.5",
    "com.unity.mathematics": "1.2.6",
    "com.unity.test-framework": "1.1.33",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.6.4",
    "com.unity.ugui": "1.0.0",
    "com.unity.visualscripting": "1.7.8",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

    "com.unity.collections": "1.2.4", contains NativeParallelHashSet<> ?

How fix the issue?

**Comment by leoDEVa** [comment]
kindly chat with the live support on the [live chat](http://algorrand-dev.com/)

**Comment by Vytek** [comment]
@leoDEVa there is no Live Chat, your link is wrong.

**Comment by Vytek** [comment]
Ok, I understand what happened. When loading the unity sdk algorithm from unity via the package. unitypackage does not load dependencies. By putting unity.mathematics and unity.collection by hand, through Package Manager, the versions compliant with Unity 2021.3.9f1 are put. The unity.collections is 1.2.4 NOT 1.3.1 as written in the package.json dependencies. Editing by hand (in 2021 the possibility of showing all versions was disabled) and bringing 1.4.0 as suggested, the update is made and everything works correctly.

**Comment by jasonboukheir** [comment]
going to close this out! Thanks @Vytek!
