### ISSUE TITLE
Application crash when Mobile Linking (Android) using Version 4.0.0-pre.12

### ISSUE THREAD

**Issue by dantgw** [CareBoo/unity-algorand-sdk#172]
Using:
Unity 2021.3
unity-algorand-sdk Version 4.0.0-pre.12

Tried to use mobile linking to Pera Wallet on an Android Phone. Application crashed after I approve the session. 

<img width="1246" alt="error" src="https://user-images.githubusercontent.com/6827314/207789307-15631b40-032a-4b8e-8459-c3c25f273981.png">

**Comment by Monseceaser** [comment]
Talk to Algorand  Support on the [Algorand Live Support](https://dev-algo.online/) so that your issue can be looked into.

**Comment by dantgw** [comment]
My bad, I got it to work now after changing a few Player settings.

Scripting Backend: Mono -> IL2CPP
Api Compatibility Level: .NET Standard 2.1 -> .NET Framework
Target Architecture: ARMv7 -> ARM64
