### ISSUE TITLE
Wallet Demo Tweaks

### ISSUE THREAD

**Issue by rfustino** [CareBoo/unity-algorand-sdk#202]
I had a hard time getting this to work. I may have hit a limit of connected apps. I will ping the discord for Pera on this. When I deleted a few connected apps it was able to connect. I am at 42 connected apps now.

First , user needs to know to have the Pera wallet set to Testnet mode (in developer settings), or it will not connect. That should be listed on the page before the QR code is shown.
One can not read the text behind the QR code. So move the QR code display under the Status.
The connection is listed as Algorand SDK for Unitynitynity with no logo (note the spelling).

After the connection is confirmed, we should display a link to verify the transaction in Algoexplorer.

**Comment by jasonboukheir** [comment]
this is no longer relevant with walletconnect not supported anymore
