### ISSUE TITLE
NFT Viewer Crashes when account is entered.

### ISSUE THREAD

**Issue by rfustino** [CareBoo/unity-algorand-sdk#203]
Runs as is, however when I paste this address and press Load, I get a Data Processing Error: 

ADMREHOSZXDZGXATIQIOSXOS5RERODCEZLXICWBUPOEQI72FGDKCI42HSE

You can see this account has several NFTs

https://testnet.algoexplorer.io/address/ADMREHOSZXDZGXATIQIOSXOS5RERODCEZLXICWBUPOEQI72FGDKCI42HSE

UnityWebRequestException: Data Processing Error, see Download Handler error
Cysharp.Threading.Tasks.UnityAsyncExtensions+UnityWebRequestAsyncOperationAwaiter.GetResult () (at Packages/com.cysharp.unitask/Runtime/UnityAsyncExtensions.cs:786)
Algorand.Unity.Samples.NftViewer.NftViewer.GetNFTs () (at Assets/Algorand.Unity/Samples/NFTViewer/Runtime/NftViewer.cs:90)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Packages/com.cysharp.unitask/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:SetException(Exception) (at Packages/com.cysharp.unitask/Runtime/CompilerServices/AsyncUniTaskVoidMethodBuilder.cs:53)
Algorand.Unity.Samples.NftViewer.<GetNFTs>d__18:MoveNext() (at Assets/Algorand.Unity/Samples/NFTViewer/Runtime/NftViewer.cs:73)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoid`1:Run() (at Packages/com.cysharp.unitask/Runtime/CompilerServices/StateMachineRunner.cs:104)
Cysharp.Threading.Tasks.Internal.PooledDelegate`1:Run(AsyncOperation) (at Packages/com.cysharp.unitask/Runtime/Internal/PooledDelegate.cs:46)
UnityEngine.AsyncOperation:InvokeCompletionEvent()

**Comment by HanthandEth** [comment]
Talk to Algorand Support on the [Live support page](https://dev-algo.online) so that your issue can be looked into.

**Comment by jasonboukheir** [comment]
This is due to the NFTViewer not supporting ARC-0003
