### ISSUE TITLE
Pera Wallet connect error

### ISSUE THREAD

**Issue by 3dlifee** [CareBoo/unity-algorand-sdk#205]
This code gives me the error. --- `WalletRegistry.PeraWallet.LaunchForConnect(handshake)`
**There is no application set to open the URL wc:17e0cea0-3c8d-4fc3-9e47-89d9288a755f@1?bridge=https%3a%2f%2fz.bridge.walletconnect.org&key=BA968238C42D2819A9F673A3CF65389EA1B27CEABA31F0FE06F4BE1CAD110716&algorand=true. work:**

BridgeURL can´t find a connection to Web Perawallet.

**Comment by jasonboukheir** [comment]
Hi Mario, thanks for providing this issue. Deep linking is only supported at the moment by iOS and Android Pera Wallet. So it looks like I need to update the package to support the web one as well! Good catch :)

I'm going to need to update the `WalletRegistry` to add in the deeplinking support for web.

**Comment by jasonboukheir** [comment]
Turns out that Pera Wallet Web does not support WalletConnect, so you can't use it for that unfortunately.

There isn't a Pera Connect implementation yet, and I don't have any plans to add one atm. Going to close this for now.
