### ISSUE TITLE
DllNotFoundException: libsodium AlgoSdk.Crypto.Random..cctor

### ISSUE THREAD

**Issue by emaadgh** [CareBoo/unity-algorand-sdk#55]
Hi, I'm testing unity-algorand-sdk in Unity 2020.3.21f1, First, I added the plugin with Open UPM like this: 

> cd my unity project location
> openupm add com.careboo.unity-algorand-sdk

that I get this result at the end: 

> notice manifest added com.careboo.unity-algorand-sdk@1.1.0
notice please open Unity project to apply changes

Then after I'm calling 

`var (privateKey, address) = Account.GenerateAccount();` 

from sample code in the [Quickstart ](https://careboo.github.io/unity-algorand-sdk/main/manual/quickstart.html)I'm getting following error : 

> DllNotFoundException: libsodium
AlgoSdk.Crypto.Random..cctor () (at Library/PackageCache/com.careboo.unity-algorand-sdk@1.1.0/CareBoo.AlgoSdk.Crypto/Random.cs:12)
Rethrow as TypeInitializationException: The type initializer for 'AlgoSdk.Crypto.Random' threw an exception.
AlgoSdk.Account.GenerateAccount () (at Library/PackageCache/com.careboo.unity-algorand-sdk@1.1.0/CareBoo.AlgoSdk/Account.cs:14)

I like to mention that I tested in both "PC standalone" and "Android" platforms and the result was the same.

I would appreciate any help.

**Comment by jasonboukheir** [comment]
Hi @emaadgh 

could you let me know what OS you're on (windows, mac, or linux)? Looks like the libsodium library isn't correctly loading

**Comment by jasonboukheir** [comment]
Ahh I see, PC is Windows. Do you know what architecture you're running? x86_64 vs x86? What architecture for arm?

**Comment by emaadgh** [comment]
Thanks for your answer, 
Yes, I'm running on Windows 10 Pro 21H1 OS and it is a 64-bit operating system, x64-based processor.

**Comment by jasonboukheir** [comment]
Hmm, sorry @emaadgh, I'm having trouble replicating the issue. Could you help me out with a couple more things to track down what's wrong?

Are the scripts you're using inside of an assembly definition?

**Comment by emaadgh** [comment]
I made a sample project for you in Unity 2020.3.21f1. I made a script that contains the code I mentioned above that has been attached to the camera object in Sample Scene for the test. I checked it on my laptop and my PC and the result was the same.

[SampleProject.zip](https://github.com/CareBoo/unity-algorand-sdk/files/7478138/SampleProject.zip)

**Comment by jasonboukheir** [comment]
> No problem, I made a sample project for you in Unity 2020.3.21f1. I made a script that contains the code I mentioned above that has been attached to the camera object in Sample Scene for the test. I checked it on my laptop and my PC and the result was the same.
> 
> [SampleProject.zip](https://github.com/CareBoo/unity-algorand-sdk/files/7478138/SampleProject.zip)

Weird, I did the following:
- Run SampleScene in editor on MacOS and Windows 11
- Make a PC Standalone x86_64 and x86 architecture using mono, run on Windows 11
- Make the build using android arm64 architecture



I wonder if it's specific to IL2CPP? Could you 
1. add the following line to your `Packages/manifest.json` `dependencies`:
```
"dependencies": {
    "com.unity.upm.develop": "0.2.0-preview",
}
```
2. Open the Package Manager window inside your project.
3. Click on the `Algorand SDK` package
4. Click the "Develop" button. This should let you modify the files inside the Algorand SDK package.
5. Edit the `Packages/Algorand SDK/CareBoo.AlgoSdk.Crypto/Interop/sodium.cs`, changing `libsodium` to `libsodium.dll`
```csharp
#if (UNITY_IPHONE || UNITY_WEBGL)
        internal const string Library = "__Internal";
#elif (UNITY_EDITOR_OSX || UNITY_STANDALONE_OSX)
        internal const string Library = "sodium";
#else
        internal const string Library = "libsodium.dll"; // Change this line here to libsodium.dll
#endif
```
6. Then try it again?

If it still fails then there's a bigger problem. If it succeeds, then I should be able to get a real fix tonight.

Currently trying to get a windows 10 VM setup to see if it's specific to that version.

**Comment by jasonboukheir** [comment]
2 last things I'd like to see
1. Have you tried reimporting the package?
2. Does it work  when running in the editor?

**Comment by emaadgh** [comment]
> Weird, I did the following:
> 
> * Run SampleScene in editor on MacOS and Windows 11
> * Make a PC Standalone x86_64 and x86 architecture using mono, run on Windows 11
> * Make the build using android arm64 architecture
> 
> I wonder if it's specific to IL2CPP? Could you
> 
> 1. add the following line to your `Packages/manifest.json` `dependencies`:
> 
> ```
> "dependencies": {
>     "com.unity.upm.develop": "0.2.0-preview",
> }
> ```
> 
> 1. Open the Package Manager window inside your project.
> 2. Click on the `Algorand SDK` package
> 3. Click the "Develop" button. This should let you modify the files inside the Algorand SDK package.
> 4. Edit the `Packages/Algorand SDK/CareBoo.AlgoSdk.Crypto/Interop/sodium.cs`, changing `libsodium` to `libsodium.dll`
> 
> ```cs
> #if (UNITY_IPHONE || UNITY_WEBGL)
>         internal const string Library = "__Internal";
> #elif (UNITY_EDITOR_OSX || UNITY_STANDALONE_OSX)
>         internal const string Library = "sodium";
> #else
>         internal const string Library = "libsodium.dll"; // Change this line here to libsodium.dll
> #endif
> ```
> 
> 1. Then try it again?
> 
> If it still fails then there's a bigger problem. If it succeeds, then I should be able to get a real fix tonight.
> 
> Currently trying to get a windows 10 VM setup to see if it's specific to that version.

I followed these steps and the issue persist. 



> Also the following would be good to see
> 
> 1. Have you tried reimporting the package?
> 2. Does it work  when running in the editor?

1. Yes I tried reimporting, also I tried on my laptop (Windows 10 Home 20H2) and the result was the same.
2. No, it does not work on the editor either.

**Comment by jasonboukheir** [comment]
Hi there @emaadgh , I went through the unity documentation, and I wonder if the "lib" prefix could be causing issues. I made a new prerelease version that I'd like you to try out (automation is saying it's fixed, but I need to make a build to check it). Please try out version 1.1.1-pre.1 and let me know if that fixed it.

If not, could you upload a zip file of the package that's installed on your machine? If you still have it set to develop, then it should be in your `Packages` directory, otherwise it will be in your `Library/PackageCache` directory.

**Comment by emaadgh** [comment]
Hi Jason, Thanks for your effort here.

I first removed previous version with :

> openupm remove com.careboo.unity-algorand-sdk

And then reinstalled the package, But the result was the same:

> DllNotFoundException: sodium
AlgoSdk.Crypto.Random..cctor () (at Library/PackageCache/com.careboo.unity-algorand-sdk@1.1.1-pre.1/CareBoo.AlgoSdk.Crypto/Random.cs:12)
Rethrow as TypeInitializationException: The type initializer for 'AlgoSdk.Crypto.Random' threw an exception.
AlgoSdk.Account.GenerateAccount () (at Library/PackageCache/com.careboo.unity-algorand-sdk@1.1.1-pre.1/CareBoo.AlgoSdk/Account.cs:14)

Here is the zipped package that you mentioned:

[com.careboo.unity-algorand-sdk@1.1.1-pre.1.zip](https://github.com/CareBoo/unity-algorand-sdk/files/7488190/com.careboo.unity-algorand-sdk%401.1.1-pre.1.zip)

Regards.

**Comment by jasonboukheir** [comment]
thanks for working with me on this! 

could you try using http://dependencywalker.com/ and drop the `sodium.dll` into it?

**Comment by emaadgh** [comment]
I used sodium.dll that was in the windows build of the project that exist in samplegame_Data\Plugins\x86_64 and here is the result : 

![Cap222ture](https://user-images.githubusercontent.com/10380342/140581295-781c8606-f966-42bf-a28e-5f64b90dd4d1.JPG)

in the log there is this error : 

> Error: At least one required implicit or forwarded dependency was not found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

**Comment by jasonboukheir** [comment]
Hi @emaadgh,

could you scroll through the dlls on the left and see which one is not found?

**Comment by emaadgh** [comment]
Hi Jason, 
I just got my hands dirty and added "libsodium 1.0.18 for .net core" in Visual Studio from NuGet by myself and replaced the libsodium.dll   in "com.careboo.unity-algorand-sdk\Plugins\Windows\x86_64"  with the one in "libsodium.1.0.18\runtimes\win-x86\native".

Now the error is gone and the code is working in Editor and Windows platform.

I attached the DLL file for you to check it out.

[libsodium.zip](https://github.com/CareBoo/unity-algorand-sdk/files/7491079/libsodium.zip)

**Comment by jasonboukheir** [comment]
@emaadgh glad you figured out the problem!

I went ahead and replaced the DLLs with the Release DLLs from Nuget (the original ones were Debug DLLs from the libsodium repository). I'm still not 100% sure why they weren't loading in your case, but I suspect there may be a dependency specific to the Debug builds that is missing. Either way, good to know that just replacing the DLL manually can fix the problem.
